### ISSUE TITLE
CONTRIBUTING.MD 

### ISSUE THREAD

**Issue by BTANISHA11** [SR-Sunny-Raj/Hacktoberfest2022-for-all#6]
I want to add contributing.md file where I will specify how to make a PR 
How to create a new branch
How to create an issue
Can you pls assign this to me @SR-Sunny-Raj

**Comment by BTANISHA11** [comment]
done @SR-Sunny-Raj

**Comment by SR-Sunny-Raj** [comment]
Sorry to inform but this repository has been excluded from hacktoberfest. So inorder to make your PR count towards hacktoberfest, request you to make your contribution in this repository -> https://github.com/SR-Sunny-Raj/Hacktoberfest2022-for-everyone
